name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: xbeach-toolbox
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Install pylint
        shell: bash -l {0}
        run: |
          conda install -y pylint

      - name: Analysing the code with pylint
        shell: bash -l {0}
        run: |
          pylint $(git ls-files '*.py')
